[server]
headless = true
enableCORS = false
maxUploadSize = 200

[theme]
base = "dark"
backgroundColor = "#070d0b"
secondaryBackgroundColor = "#0e1714"
primaryColor = "#00b894"
textColor = "#dfe6e9"
font = "monospace"
